version: '3.5'

services:
  app:
    build: .
    ports:
      - 3000:1337
    expose:
      - 3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app

volumes:
  node_modules:
